name: "Fan out changes to distinct repositories"

on:
  push:
    branches:
      - "main"

concurrency: fanout-${{ github.ref }}

jobs:
  fanout:
    strategy:
      matrix:
        parts:
          - dir: "addons/streamtoy-client"
            repo: "deep-entertainment/godot-streamtoy-client"
    name: "Fanout ${{ matrix.parts.dir }} to ${{ matrix.parts.repo }}"
    runs-on: "ubuntu-20.04"
    env:
      DIR: "${{matrix.parts.dir}}"
      REPO: "${{matrix.parts.repo}}"
    steps:
      - name: "Configure git"
        run: |
          if ! git --version | grep 2.33 >/dev/null
          then
              sudo add-apt-repository ppa:git-core/ppa -y
              sudo apt-get update
              sudo apt-get install git -y
          fi
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          repository: "deep-entertainment/godot-streamtoy-template"
          ref: "develop"
          path: "template"
          token: "${{ secrets.DEPLOYMENT_TOKEN }}"
          fetch-depth: 0
      - name: "Filtering out ${{ env.DIR }}"
        run: |
          curl -s https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo -o git-filter-repo
          chmod +x git-filter-repo
          cd template
          git remote -v
          ../git-filter-repo --path $DIR --prune-empty auto --force
          git clean -fd
          git status
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          repository: "${{ env.REPO }}"
          ref: "main"
          path: "target"
          token: "${{ secrets.DEPLOYMENT_TOKEN }}"
          fetch-depth: 0
      - name: "Apply changes"
        run: |
          cd target
          git config --global user.email "info@deep-entertainment.de"
          git config --global user.name "deep entertainment merge bot"
          git pull ../template develop --rebase
          git push --force
